#pragma once

/*
    Minimal Reed-Solomon encoding and decoding library for embedded use, intended
    for sending packets over unreliable links.

    The encoding uses the Galois Field GF(2^8) with hardcoded primitive polynomial
    x^8 + x^4 + x^3 + x^2 + 1.

    No dynamic memory allocation — the caller provides any needed workspace.
*/

#include <stdint.h>
#include <stddef.h>

// Workspace size (in bytes) needed by rs_encode_init() / rs_encode().
// Holds the precomputed generator polynomial (degree N-K).
#define RS_ENCODE_WORKSPACE(N, K)  ((N) - (K) + 1)

// Scratch size (in bytes) needed by rs_decode().
#define RS_DECODE_SCRATCH(N, K)    (4 * ((N) - (K)))

// rs_encode_init() precomputes the generator polynomial for the given K and N.
// This only needs to be called once for a given (K, N) pair; the resulting
// workspace can then be reused across multiple rs_encode() calls.
// The caller must provide a workspace of at least RS_ENCODE_WORKSPACE(N, K) bytes.
void rs_encode_init(uint8_t K, uint8_t N, uint8_t* work, size_t work_len);

// rs_encode() takes a buffer buf[0:N], and two numbers K and N such that 0 < K < N <= 255.
// The first K bytes, buf[0:K] contain the payload data.
// rs_encode() then fills buf[K:N] with N-K error correction bytes.
// work must have been initialized by rs_encode_init() with the same K and N.
void rs_encode(uint8_t* buf, uint8_t K, uint8_t N, uint8_t* work);

// rs_decode() takes a buffer buf[0:N] and two numbers K and N such that 0 < K < N <= 255.
// buf must have been generated by rs_encode() with the same values for K and N.
// rs_decode() then tries to find and correct the errors in buf[0:N].
// It returns the number of errors corrected, or -1 if there were more errors than could be corrected.
// The caller must provide scratch space of at least RS_DECODE_SCRATCH(N, K) bytes.
int rs_decode(uint8_t* buf, uint8_t K, uint8_t N, uint8_t* scratch, size_t scratch_len);
